### ISSUE TITLE
JSON schema validation error when including annotations for @interface.

### ISSUE THREAD

**Issue by GuusVink** [Ali-chakaroun/ISEP-LivingDocumentation#131]
The Analyzer does not seem to work well with annotation interfaces. Results in the output JSON to contain a type without a FullName.
Resulting error:
```
net.jimblackler.jsonschemafriend.ListValidationException: Validation errors: {"Type":"java.lang.annotation.Retention","Name":"Retentio... at #/3 failed against file:/C:/.../ISEP-LivingDocumentation/analyzer-java/target/classes/jsonschema/schema.json#/items with "Missing property FullName"
"java.lang.annotation.Retention" at #/3/Type failed against file:/C:/.../ISEP-LivingDocumentation/analyzer-java/target/classes/jsonschema/schema.json#/items/properties/Type with "Expected: [integer] Found: [string]"
[{"Name":"value","Type":"java.lang.annotation.RetentionPo... at #/3/Arguments failed against file:/C:/.../ISEP-LivingDocumentation/analyzer-java/target/classes/jsonschema/schema.json#/items/additionalProperties with "False"
"Retention" at #/3/Name failed against file:/C:/.../ISEP-LivingDocumentation/analyzer-java/target/classes/jsonschema/schema.json#/items/additionalProperties with "False"
	at net.jimblackler.jsonschemafriend.Validator.validate(Validator.java:715)
	at com.infosupport.ldoc.analyzerj.Analyzer.validateJson(Analyzer.java:59)
	at com.infosupport.ldoc.analyzerj.Analyzer.analyze(Analyzer.java:90)
	at com.infosupport.ldoc.analyzerj.Main.main(Main.java:42)
```

Reproducing error:
annotation interface with added annotation, e.g.,:
```
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface AnnotationTest {

  String testField() default "";
}
```

**Comment by wandernauta** [comment]
Indeed, good find - it looks like we do not currently override `visit(AnnotationDeclaration n, Analyzer arg)` in `AnalysisVisitor`, but should (and probably treat it similar to `ClassOrInterfaceDeclaration`'s interface case).

**Comment by GuusVink** [comment]
Decision: mark @interface as interface in JSON
