### ISSUE TITLE
Analyzer exception when record part of method call argument

### ISSUE THREAD

**Issue by GuusVink** [Ali-chakaroun/ISEP-LivingDocumentation#140]
To reproduce the issue:

```
public record TestRecord(int id, String name) {}
```

```
class TestClass {

  void dummyMethod() {
    TestRecord recVar = new TestRecord(1, "string");
    test(recVar);
  }
  void test(TestRecord testRecord) {}
}

```

Which yields an IllegalArgumentException:

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot get a reference type declaration from com.github.javaparser.ast.body.RecordDeclaration
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.toTypeDeclaration(JavaSymbolSolver.java:317)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeDeclaration(JavaParserFacade.java:701)
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveTypeUncached(JavaParserTypeSolver.java:287)
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveType(JavaParserTypeSolver.java:253)
        at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:161)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:185)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:151)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:101)
        at com.github.javaparser.resolution.Context.solveTypeInParentContext(Context.java:154)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractMethodLikeDeclarationContext.solveType(AbstractMethodLikeDeclarationContext.java:122)
        at com.github.javaparser.resolution.Context.solveType(Context.java:97)
        at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:345)
        at com.github.javaparser.ast.type.ClassOrInterfaceType.lambda$convertToUsage$3(ClassOrInterfaceType.java:352)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:352)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:609)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:642)
        at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration.getReturnType(JavaParserMethodDeclaration.java:87)
        at com.github.javaparser.resolution.MethodUsage.<init>(MethodUsage.java:55)
        at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.lambda$getDeclaredMethods$2(ReferenceTypeImpl.java:163)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.getDeclaredMethods(ReferenceTypeImpl.java:161)
        at com.github.javaparser.symbolsolver.logic.AbstractTypeDeclaration.getAllMethods(AbstractTypeDeclaration.java:67)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.toMethodUsage(JavaParserFacade.java:407)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:628)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
        at com.github.javaparser.ast.expr.MethodReferenceExpr.accept(MethodReferenceExpr.java:93)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:503)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:350)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:332)
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:294)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:387)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:72)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:118)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1760)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.body.VariableDeclarator.accept(VariableDeclarator.java:145)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.lambda$visit$0(GenericListVisitorAdapter.java:1847)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1847)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1744)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.expr.VariableDeclarationExpr.accept(VariableDeclarationExpr.java:114)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:767)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:73)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.lambda$visit$0(GenericListVisitorAdapter.java:1847)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1847)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:297)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:266)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:72)
        at com.github.javaparser.ast.body.ConstructorDeclaration.accept(ConstructorDeclaration.java:92)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.lambda$visit$0(GenericListVisitorAdapter.java:1847)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1847)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.typeBuilder(AnalysisVisitor.java:116)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:129)
        at com.infosupport.ldoc.analyzerj.AnalysisVisitor.visit(AnalysisVisitor.java:72)
        at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:94)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.lambda$visit$0(GenericListVisitorAdapter.java:1847)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:1847)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.NodeList.accept(NodeList.java:275)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:501)
        at com.github.javaparser.ast.visitor.GenericListVisitorAdapter.visit(GenericListVisitorAdapter.java:45)
        at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:126)
        at com.infosupport.ldoc.analyzerj.Analyzer.analyze(Analyzer.java:82)
        at com.infosupport.ldoc.analyzerj.Main.main(Main.java:46)
```

**Comment by wandernauta** [comment]
Is this the same issue as #66?

**Comment by GuusVink** [comment]
Seems like it. Should the issues be merged, or should this issue be deleted?
