### ISSUE TITLE
UnresolvedSymbolException

### ISSUE THREAD

**Issue by eNeRGy164** [Ali-chakaroun/ISEP-LivingDocumentation#154]
When running the analyzer on a certain code base, ran into this exception:

```plain
Exception in thread "main" UnsolvedSymbolException{context='null', name='AbstractEntity', cause='null'}
	at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:347)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:609)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:620)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:284)
	at com.infosupport.ldoc.analyzerj.AnalysisVisitor.resolve(AnalysisVisitor.java:89)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
```

class:

```java
import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import java.time.Instant;
import lombok.Getter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

@Getter
@MappedSuperclass
public abstract class AbstractEntity {

    @CreationTimestamp
    @Column(name = "created", nullable = false, updatable = false)
    private Instant created;

    @UpdateTimestamp
    @Column(name = "last_updated")
    private Instant lastUpdated;
}
```

executed with:

```sh
java -jar .\analyzer-java\target\analyzer-java-1-SNAPSHOT-shaded.jar --classpath <path-to-jar>.jar --output service.json --project <path-to-root-dir>
```

Not sure if this is due to some code not supported by the analyzer, but as it only references public dependencies I could share the actual code.

**Comment by GuusVink** [comment]
Hey Michaël, first of all, thanks for testing the Analyzer on your codebase.

First two questions regarding how you call the analyzer (to exclude some possible problems):

1. (Assuming this is a Maven project) is does the path under --project point to the source root (so ending with src/main/java)? Otherwise, the analyzer will not look in the proper place for classes.
2. Are all the JARs that are needed to compile the project listed under --classpath (i.e., all the dependencies)? We would expect multiple JARs separated by ';'. 

If both these points are set correctly, it could also well be a limitation found in JavaParser type resolvement mechanisms (of which we found multiple). We are currently working on mitigating this in #153.

Regardless of the cause, regarding the two questions on running the analyzer via the command line, it might be good for us to provide a bit more guidance regarding these possible mistakes.

**Comment by eNeRGy164** [comment]
I did point to the root of the project (where the POM is), not `src/main/java` :) I would expect the property to be called "source-root" or something. (but I'm the newbie here 😉)

The POM is containing all dependencies (a fat-jar)

I will try to run this again later, now I have to make a 13:45h appointment 😉

**Comment by eNeRGy164** [comment]
Adding `/src/main/java` indeed makes a difference:

```
Exception in thread "main" UnsolvedSymbolException{context='null', name='We are unable to find the annotation declaration corresponding to @Id', cause='null'}
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:265)
	at com.infosupport.ldoc.analyzerj.AnalysisVisitor.resolve(AnalysisVisitor.java:103)
```

**Comment by wandernauta** [comment]
Thanks for testing, that's good to hear!

Guessing that that `@Id` is supposed to be `javax.persistence.Id` or `jakarta.persistence.Id` or similar, a next step would be to make sure that that annotation (or the JAR that provides it) is indeed on the analysis classpath. To do type resolution, the analysis classpath should really have all the JARs that are needed to compile the code – providing just the JARs that the code needs at runtime is not sufficient. (The Maven and Gradle plugins should set this automatically.)

If you would be alright with the output JSON not including type information for these things, then it might be worthwhile to update to the latest `main`, which has #153 merged and so should just put a "?" in the places it can't resolve. But providing a JAR containing the `Id` annotation would make the output more useful.

Issue #155 is about making the logging a bit more developer-friendly in this case.
